// tslint:disable
/**
 * Movie Reviews
 * With the Movie Reviews API, you can search New York Times movie reviews by keyword and get lists of NYT Critics\' Picks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";
